{% set name = "jax-tqdm" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jax_tqdm-{{ version }}.tar.gz
  sha256: 6a70971e231d3930a8beda5032e39498ae06f9c4ba645a4cf7c02cd363eba991

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.2.0
    - pip
  run:
    - python >=3.8
    - tqdm >=4.64.1,<5.0.0
    - jax >=0.3.5

test:
  imports:
    - jax_tqdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jeremiecoullon/jax-tqdm
  summary: Tqdm progress bar for JAX scans and loops
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
