{% set name = "jax-tqdm" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jax_tqdm-{{ version }}.tar.gz
  sha256: b76b3ecc334b91f414f52740c28c1aa85bb75eb8d1a0048b5723db3dd4812a1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >={{ python_min }}
    - tqdm >=4.64.1,<5.0.0
    - jax >=0.3.5
    - chex

test:
  imports:
    - jax_tqdm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jeremiecoullon/jax-tqdm
  summary: Tqdm progress bar for JAX scans and loops
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
